apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: app-director-manager-rolebinding
  labels:
    {{- include "labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: app-director-manager-role
subjects:
- kind: ServiceAccount
  name: {{ template "app-director-operator.serviceAccountName" . }}
  namespace: {{ include "app-director-operator.namespace" . }}