apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-director-leader-election-role
  namespace: {{ include "app-director-operator.namespace" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  - coordination.k8s.io
  resources:
  - configmaps
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch