apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-director-leader-election-rolebinding
  namespace: app-director
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app-director-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: app-director