apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-director-leader-election-rolebinding
  namespace: {{ include "app-director-operator.namespace" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app-director-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ template "app-director-operator.serviceAccountName" . }}
  namespace: {{ include "app-director-operator.namespace" . }}