apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    {{- include "labels" . | nindent 4 }}
  name: app-director-controller-manager-metrics-service
  namespace: {{ include "app-director-operator.namespace" . }}
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: controller-manager