annotations:
  category: DeveloperTools
apiVersion: v2
appVersion: 0.1.0
description: Keycloak is a high performance Java-based identity and access management solution. It lets developers add an authentication layer to their applications with minimum effort.
home: https://www.keycloak.org
icon: https://bitnami.com/assets/stacks/keycloak/img/keycloak-stack-220x234.png
keywords:
- app-director
- app-director-operator
- randoli
maintainers:
- name: Randoli
  url: https://randoli.ca
  email: support@randoli.ca
name: app-director-operator
sources:
- https://github.com/randoli/app-director-operator
version: 0.8.0
